### ISSUE TITLE
Future Updates

### ISSUE THREAD

**Issue by ryandw11** [ryandw11/CustomStructures#101]
**Future Update:**
- [ ] Child Structures
- [ ] World Guard Regions
- [ ] Spawn dirt in air spaces under a structure.

**Comment by SwordandKeyboard** [comment]
how are these coming? looking forward to it, child structures especially.

**Comment by ryandw11** [comment]
I haven't made it very far with the updates. I've been a little busy recently with not much time to work on the plugin. The most difficult part about the first two are figuring out how the configuration for them will be structured. I also need to fit them in with the current configuration format.

**Comment by SwordandKeyboard** [comment]
You could have a conpiled structure with a sign post at the center of the structure, /child [range from sign] [density] [max to create] maybe? Then whitelist the schematics it can use in the config? I have a really surface level knowledge of Java (and coding in general)
