### ISSUE TITLE
Mythic mobs doesn't spawn in structures

### ISSUE THREAD

**Issue by TheBeast434** [ryandw11/CustomStructures#104]
When a structure is naturally spawned the mythic mobs does not

they should spawn

https://pastebin.com/Yvdr9syj

 - Minecraft Version: 1.16.4
 - Paper Version: 1.16.4
 - Custom Structures Version: 1.5.6
 - World Edit Version: 7.2.0

**Comment by ryandw11** [comment]
Can you send a screenshot of your sign? Does anything appear in the console?

**Comment by TheBeast434** [comment]
![2020-12-23_23 55 29](https://user-images.githubusercontent.com/73647900/103042620-808d4280-457a-11eb-9802-9732d84cd890.png)
![2020-12-23_23 55 03](https://user-images.githubusercontent.com/73647900/103042623-82ef9c80-457a-11eb-9a16-05b152d6173e.png)
![2020-12-23_23 55 00](https://user-images.githubusercontent.com/73647900/103042624-8420c980-457a-11eb-9762-7ff6d8613c0f.png)
![2020-12-23_23 54 56](https://user-images.githubusercontent.com/73647900/103042627-85ea8d00-457a-11eb-8b82-bc4b4a595978.png)

**Comment by TheBeast434** [comment]
nothing appear in the console

**Comment by ryandw11** [comment]
What is the name of your mob according the mythical mobs?

**Comment by TheBeast434** [comment]
minionnavenorm and minion_nave_norm

**Comment by ryandw11** [comment]
I'm not certain what is happening. Can you spawn normal mobs with structures?

**Comment by TheBeast434** [comment]
yes

**Comment by TheBeast434** [comment]
ryandw11 
I fixed the problem

**Comment by ryandw11** [comment]
What was the issue?

**Comment by TheBeast434** [comment]
you have to put false in this string in the mythic mobs config
![ffff](https://user-images.githubusercontent.com/73647900/103159926-a1020a80-47cf-11eb-9a17-a255e8dfac80.PNG)

**Comment by ryandw11** [comment]
Thank you for pointing that out. I'll put that in the documentation for others to know about.
