### ISSUE TITLE
Loot tables not working

### ISSUE THREAD

**Issue by TheCastes** [ryandw11/CustomStructures#105]
Whenever I load a specific structure, nothing is inside the loot tables, I used the template one to be sure nothing was written wrong in my table. Only one specific structure does not work as intended.

https://pastebin.com/2RUhKMej (structure file)
https://pastebin.com/6SUNKWRB (my loot table)
[castellone.zip](https://github.com/ryandw11/CustomStructures/files/5745308/castellone.zip)

 - Minecraft Version: 1.16.4
 - Paper Version: 1.16.4-345
 - Custom Structures Version: 1.5.6

 - World Edit Version: 7.2.0

**Comment by ryandw11** [comment]
You have an invalid config format. The format was changed in 1.5.6.
See: 
https://github.com/ryandw11/CustomStructures/wiki/Structure-Formatting#loot-tables
and
https://github.com/ryandw11/CustomStructures/wiki/Loot-Tables
for the correct format.

**Comment by xXTheBeast434Xx** [comment]
we have a problem if we modify the config it tells us that the structure does not exist
 i work with him

**Comment by TheBeast434** [comment]
we have a problem if we modify the config it tells us that the structure does not exist
i work with him

**Comment by Sam1000000** [comment]
and if we switch the current loot table with a loot table from another dungeon the mobs doesn't spawn and the loot table doesn't work

the problem with the mobs is like that https://github.com/ryandw11/CustomStructures/issues/23 but with the mythic mob instead of the normal mob

**Comment by ryandw11** [comment]
Check the consoles for errors.

**Comment by xXTheBeast434Xx** [comment]
no errors

**Comment by TheBeast434** [comment]
ERROR Cannot load plugins/CustomStructures/lootTables/CastelloneLT.yml
28.12 01:30:01 [Server] WARN For more information please check to wiki.
28.12 01:30:01 [Server] WARN Structure file: castellone.yml does not exist! Did you make a new structure file in the Structure folder?

**Comment by ryandw11** [comment]
In the config.yml the plugin cannot find castellone. Can I see your config.yml?

**Comment by Sam1000000** [comment]
https://we.tl/t-z6tCFZm9kE this is te config of cstructures

**Comment by ryandw11** [comment]
Please use pastebin: https://pastebin.com/

**Comment by Sam1000000** [comment]
https://pastebin.com/e7K5A21Q

**Comment by Sam1000000** [comment]
https://pastebin.com/5qi4kq9Q sorry, i've noticed that the previus pastebin was expired.

We have made some tests with the castellone and castellone1 because a problem with the schematics, the original (or the one that we use) is castellone1

**Comment by TheBeast434** [comment]
we solved the problem thanks for your help

**Comment by ryandw11** [comment]
May I asked what the issue was?

**Comment by TheBeast434** [comment]
the problem was that if we modify the config the dungeon castellone doesn't work

**Comment by ryandw11** [comment]
How did you fix the issue?

**Comment by TheBeast434** [comment]
I downgraded to version 1.5.5
