### ISSUE TITLE
Is it possible to prevent structures from spawning inside other structures or floating?

### ISSUE THREAD

**Issue by googleooer** [ryandw11/CustomStructures#106]
BlockLevelLimit and SpawnY don't seem to be working.

What it looks like in-game:

![error_plugin_1](https://user-images.githubusercontent.com/35429559/108899100-c7d59500-75f6-11eb-91bb-9e3e1e1ca76c.png)

My structure:

```schematic: bigshroom_empty.schem
Chance:
  Number: 90
  OutOf: 100
StructureLocation:
  Worlds:
  - creative
  SpawnY: '-9'
  CalculateSpawnFirst: true
  Biome: []
StructureProperties:
  PlaceAir: false
  randomRotation: false
  ignorePlants: true
  spawnInWater: false
  spawnInLavaLakes: false
StructureLimitations:
  whitelistSpawnBlocks:
  - Grass_block
  - Mycelium
  replacement_blocks:
    'GLASS': 'AIR'
  replacement_blocks_delay: 1
BlockLevelLimit:
    # Can be flat or flat_error.
    mode: flat
    cornerOne:
      x: -25
      z: -25
    cornerTwo:
      x: 25
      z: 25```

**Comment by googleooer** [comment]
I fixed the issue that made it spawn in the ocean by setting CalculateSpawnFirst to false, however, it seems like it calculates the flat area and the spawn block with the corner block. It would be nice if you added a way to set an offset.

**Comment by ryandw11** [comment]
If you save the schematic with `//copy` and use `//schem save` it will work properly. I am looking into fixing the corner thing when using `/cstruct createschem`.

**Comment by googleooer** [comment]
I see, thank you.

**Comment by googleooer** [comment]
It recognizes the center properly now, but it seems like the BlockLevelLimit settings still aren't working.


![error_plugin_2](https://user-images.githubusercontent.com/35429559/109056639-704f2c00-76bf-11eb-8903-7e05b09d266e.png)

**Comment by ryandw11** [comment]
Did the block level limit work before changing the center?

**Comment by googleooer** [comment]
No, it didn't
