### ISSUE TITLE
Structure Spawning

### ISSUE THREAD

**Issue by OmikronOverload** [ryandw11/CustomStructures#108]
**Describe the bug**
I noticed it while testing structure spawning in a world.
Basically structures spawn at they'r lowest point, not the point where you /cstruct createschem.
Anything you would possibly want to spawn lower like an indent for example making a fountain 5 blocks deep wouldnt work.

**Steps to Reproduce**
Build something which goes into the ground, do the worldedit thing corner1, corner2 putting it in the config ready to spawn.

**Expected behavior**
Should spawn as described on Spigot.

**Screenshots**
Expected to spawn 1-2 blocks lower
![2021-03-19_11 22 43](https://user-images.githubusercontent.com/69091958/111766300-aa1de780-88a5-11eb-85da-c51e29f1d7f3.png)

**Structure File(s)**
https://pastebin.com/BqcvSZSq

**Environment Information:**
 - Minecraft Version: 1.16.5
 - Spigot Version (paper): paper-1.16.5-529
 - Custom Structures Version: 1.5.6.2

 - World Edit Version: FastAsyncWorldEdit-626

**Additional context**

**Comment by OmikronOverload** [comment]
![2021-03-19_11 41 35](https://user-images.githubusercontent.com/69091958/111768327-17327c80-88a8-11eb-9f6f-30b1224256c5.png)
I think this is an good example of what a structure spawn shouldnt look like

**Comment by ryandw11** [comment]
I'll look into correcting that.

**Comment by ryandw11** [comment]
Fixed in 1.5.7. An update will be released later.

**Comment by OmikronOverload** [comment]
Awesome!
Can't wait to test it out ;)
