### ISSUE TITLE
More of 1

### ISSUE THREAD

**Issue by bruhIDFK** [ryandw11/CustomStructures#109]
Is it possible for me to make more of ONE structure? Like different kinds? And when i choose the region i want it to spawn in, is it possible to make it spawn a random version?

**Comment by ryandw11** [comment]
You could make a bunch of sub-schematics with the different versions you want. Then for the main schematic you just put a subschem sign. 
You can view about how to make subschematics [here](https://github.com/ryandw11/CustomStructures/wiki/Structure-Formatting#subschematics) and [here](https://github.com/ryandw11/CustomStructures/wiki/sub-schematics).
