### ISSUE TITLE
Support with custom biomes?

### ISSUE THREAD

**Issue by Jadestrouble** [ryandw11/CustomStructures#110]
With 1.16 datapacks custom dimension support now exists. I was using this plugin to generate structures in specific biomes that were created via these datapacks and it doesn't seem to work. this isn't that big of an issue as I could specify the world to spawn in and that works fine, but it would be neat if the plugin could do that.

**Comment by ryandw11** [comment]
As of right now spigot does not support custom biomes. See https://hub.spigotmc.org/jira/browse/SPIGOT-6073 for more information.

**Comment by ryandw11** [comment]
You can now use [this addon](https://github.com/ryandw11/CustomStructures/wiki/custom-biomes-addon) for custom biome support.
