### ISSUE TITLE
Support for itemsadder custom block

### ISSUE THREAD

**Issue by xalixilax** [ryandw11/CustomStructures#111]
While creating custom schematic with[ itemsadder](https://www.spigotmc.org/threads/%E2%9C%85must-have%E2%9C%85-itemsadder%E2%9C%A8textures-3d-models-emojis-ores-blocks-wings-tails-hats-more.412279/page-21) blocks and the [itemsadder worldedit pluggin](https://www.spigotmc.org/resources/addon-itemsadder-worldedit.79012/) or by using this plugin structure creation, the generated structures does not register in itemsadder storage. 
This mean that tested or generated structure with custom block are keeping the texture but does not drop any block when broken.
Generated structure with custom block should still have texture, drop block or register right click without being able to update the block texture.

https://pastebin.com/sN7DRtPy

 - Minecraft Version: 1.16.5
 - Spigot Version: "currentVersion":"git-Paper-\"000cec2ab\" (MC: 1.16.5)"}
 - Custom Structures Version: 1.5.7
 - World Edit Version: 7.2.4
 - Itemsadder World Edit Addon: 1.0.3

**Comment by xalixilax** [comment]
I asked loneDev and he sent me this for compatibility.
https://itemsadder.plugin.ga/compatibility-with-other-plugins/adding-compatibility

**Comment by ryandw11** [comment]
The issue with adding support for premium plugins is that I can't test them. I would have to guess the implementation for it without know if it works. Unless I find a way to test my implementation, it likely won't happen.

**Comment by xalixilax** [comment]
Yeah i can see what the issue is. What about having access to a server with both plugin installed? It could allow you to test and I have to admit, no random structure would be a real bummer for me. I'm still setting up blocks on my server and almost no config are done. I would not mind to let you full access for the time of programming/testing.
