### ISSUE TITLE
[Error] Can't spawn structures in nether.

### ISSUE THREAD

**Issue by tatanpoker09** [ryandw11/CustomStructures#114]
I've been trying to get structures to appear in the nether.
This error message is being spammed in console:
```java
12:27:30 AM [Server thread/ERROR]: [CustomStructures] An error was encountered during the schematic pasting section.
12:27:30 AM [Server thread/ERROR]: [CustomStructures] The task was stopped for the safety of your server!
12:27:30 AM [Server thread/ERROR]: [CustomStructures] For more information enable debug mode.
12:27:30 AM [WARNING] java.lang.IllegalArgumentException: Cannot measure distance between UltraCraftWorld and UltraCraftWorld_nether
12:27:30 AM [WARNING] 	at org.bukkit.Location.distanceSquared(Location.java:500)
12:27:30 AM [WARNING] 	at org.bukkit.Location.distance(Location.java:483)
12:27:30 AM [WARNING] 	at com.ryandw11.structure.structure.StructureHandler.validDistance(StructureHandler.java:158)
12:27:30 AM [WARNING] 	at com.ryandw11.structure.structure.Structure.canSpawn(Structure.java:226)
12:27:30 AM [WARNING] 	at com.ryandw11.structure.utils.StructurePicker.run(StructurePicker.java:62)
```

**Comment by tatanpoker09** [comment]
I must add that I tested spawning in the end. This worked as intended

**Comment by ryandw11** [comment]
Thanks for reporting.

**Comment by tatanpoker09** [comment]
Was this tested after the bug fix by any chance? There's no console error but I still haven't been able to get a structure to spawn. 

I'm using the following: 

```yml
schematic: NucleoDelMal.schem
Chance:
  Number: 1
  OutOf: 200
StructureLocation:
  Worlds:
  - UltraCraftWorld_nether
  SpawnY: '+1'
  CalculateSpawnFirst: false
  Biome: []
  DistanceFromOthers: 200
  spawn_distance:
    x: 10
    z: 10
StructureProperties:
  PlaceAir: true
  randomRotation: true
  ignorePlants: true
  spawnInWater: false
  spawnInLavaLakes: true
  spawnInVoid: false
StructureLimitations:
  whitelistSpawnBlocks:
  - netherrack
  - soul_sand
  - soul_soil
  - air
  - QUARTZ_ORE
  - crimson_nylium
  - lava
  - warped_nylium
  BlockLevelLimit:
    mode: flat
    cornerOne:
      x: -5
      z: -5
    cornerTwo:
      x: 5
      z: 5
  replacement_blocks:
    STONE: AIR
  replacement_blocks_delay: 0
LootTables:
  CHEST:
    tablaNucleoMal: 3
```

and so far no spawns have happened. I tried using /cstruct testspawn and got this:
![image](https://user-images.githubusercontent.com/6262015/122312454-3ca04800-cee2-11eb-8dca-df8992f3096b.png)

**Comment by tatanpoker09** [comment]
I must add that I built version 1.6.0 on my own to test this

**Comment by ryandw11** [comment]
No, this has not been tested, but that is not your issue. The issue is that the structure cannot spawn on the block that is being selected. What is the block at the center of the chunk where you ran the command?

Also, I advise against using 1.6.0 as it does change the structure configuration format. That format is also not finalized so if you use the most recent version, the auto updater in the release won't be able to fix your files for you.

**Comment by tatanpoker09** [comment]
It is netherrack, which is why I found it weird.
Problem is I need it to be able to spawn structures in the nether, which wasn't happening in the previous versions. Is there any alternative I could look into?

**Comment by tatanpoker09** [comment]
![image](https://user-images.githubusercontent.com/6262015/122324788-66179e80-cef7-11eb-9488-291459ab2708.png)
I ran it multiple times just to be sure. Based on the error message shown yesterday, could it be possible that even though I'm in the nether it is trying to spawn it in the overworld and failing at that?

**Comment by ryandw11** [comment]
I know why. The nether top is the bedrock layer at the top. So you are trying to spawn it on bedrock.

**Comment by tatanpoker09** [comment]
That solved it. Thank you very much 😄 

I suggest adding in the Wiki that only ranges and direct numbers should be used in spawnY for nether structures
