### ISSUE TITLE
[Feature Request] Fixed Y heights

### ISSUE THREAD

**Issue by Mnky313** [ryandw11/CustomStructures#119]
Is it possible to set a fixed y range for structures to spawn?

for example if I only want structure x to generate from -64 to 0 right now I don't really have a way of doing that, I can say it needs to generate 64-128 blocks below the surface but if the random point it picks is in a cave it throws an error because it tries to spawn below the world. It would also spawn structures above the desired y level when spawning under a mountain.

Would be possible to have a SpawnYHeightmap option for FIXED or something that just uses the values in SpawnY as the min and max height?

**Comment by ryandw11** [comment]
This feature should already exist. You can set SpawnY to
```yml
SpawnY: '[-64;0]'
```
Which will spawn from Y -64 to Y 0 exactly.

**Comment by Mnky313** [comment]
I thought the SpawnYHeightmap was required? I thought when I removed that line it couldn't load the structure. I'll test it again tomorrow,  sorry about that.

**Comment by ryandw11** [comment]
It is required, but it does not mean anything when the SpawnY is not relative to the surface.

It only matters for SpawnY values of: `+[4]`, `-[4]`, `+[3;5]`, `-[3;5]`.

**Comment by Mnky313** [comment]
> It is required, but it does not mean anything when the SpawnY is not relative to the surface.

Ah, thanks for the clarification
