### ISSUE TITLE
custom loot table for every structure

### ISSUE THREAD

**Issue by yellow-pillow** [ryandw11/CustomStructures#124]
its not a bug, idk how to do another issue

 ok so i want to suggest to add custom loot table for every structure
 
 for example in folder loot table make yml files with names of structures or right structure names in yml files
 
 what do you thinck about it?

**Comment by ryandw11** [comment]
Why would this be needed? You can already define new loot tables for a single structure.

**Comment by yellow-pillow** [comment]
really, how? i didn't find any information in your wiki:(
