### ISSUE TITLE
1.18 bug

### ISSUE THREAD

**Issue by soupcoup** [ryandw11/CustomStructures#128]
bug on 1.18 when doing /cstructure test and /cstructure createschem
https://pastebin.com/33kvqQLq

**Comment by ryandw11** [comment]
That is a world edit error. Please use to version of world edit for 1.18. 
You can find the 1.18 world edit builds here: https://builds.enginehub.org/job/worldedit?branch=version/7.2.x

**Comment by ryandw11** [comment]
I am going to assume that this issue is resolved. If the issue persists, please open another issue.
