### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by KingsRequin** [ryandw11/CustomStructures#132]
**Is your feature request related to a problem? Please describe.**
----
I've already wanted to have a special chest for the loot, for example a maze with lots of chests, but only one that contains rare items
-------------

**Describe the solution you'd like**
----
Be able, with a panel for example, to describe a special chest that takes a special lootTables
-------------

**Describe alternatives you've considered**
----
this could be done by placing a panel on the trunk with:

[lootTables]
lootTables1

lootTables1 would be the .yml file
-------------

**Additional context**

![2022-02-02_23 39 06](https://user-images.githubusercontent.com/61652807/152249808-4157311c-2040-40ae-815b-8b728d3a4ce8.png)

**Comment by ryandw11** [comment]
This is a feature I plan on implementing. Although I want to implement it by naming a piece of paper inside of the chest with the name of the loot table.

**Comment by KingsRequin** [comment]
ok, I have another suggestion, i put it here, or I create another issue?
