### ISSUE TITLE
Substructures not generating

### ISSUE THREAD

**Issue by KingofAnomaly** [ryandw11/CustomStructures#133]
**Describe the bug**
I can't get substructures to work. I am trying to get a variety of meteorites to spawn in a crater but it just keeps spawning the sign.

**Steps to Reproduce**
• Place the sign like the wiki says in the main schematic with an oak sign
• Save the main schematic with the sign
• Save the sub schematic
• Setup the config like the wiki says with my structure files
• Reload the plugin
**Expected behavior**
Spawn a crater with a meteorite 

**Structure File(s)**
Main structure- [crater_small.schem.zip](https://github.com/ryandw11/CustomStructures/files/8064284/crater_small.schem.zip)
Subschematic- [meteorite_small_crying-obsidian.schem.zip](https://github.com/ryandw11/CustomStructures/files/8064286/meteorite_small_crying-obsidian.schem.zip)

**Environment Information:**
 - Minecraft Version: 1.18.1
 - Paper Version: 197
 - Custom Structures Version: 1.7.1.1
 - World Edit Version: 7.2.8
 - AsyncWorldEdit Version: 3.9.3

**Additional context**
I'm new to the plugin and have played around with it for several hours to see if I could get it to work but have had no success also I have an AsyncWorldedit plugin that I think might interfere.

**Comment by ryandw11** [comment]
Since you are using AsyncWorldEdit you will need to modify the [replacement_blocks_delay](https://github.com/ryandw11/CustomStructures/wiki/Structure-Formatting#replacement-blocks-delay) option.

1.5 seconds would probably be a good time.

`replacement_blocks_delay: 1.5`

**Comment by KingofAnomaly** [comment]
Thank you! I should have read everything a little more thoroughly but thank you for helping!
