### ISSUE TITLE
Substructure generation limit

### ISSUE THREAD

**Issue by KingofAnomaly** [ryandw11/CustomStructures#134]
**Describe the bug**
I get this error when I try to make a randomly generated structure after the second set of substructures spawn in and a third set tries to spawn.
[13:30:33 ERROR]: [CustomStructures] Critical Error: StackOverflow detected. Automatically terminating the spawning of the structure.
[13:30:33 ERROR]: [CustomStructures] The structure 'demo' has spawned too many sub structure via recursion.

**Steps to Reproduce**
have substructures spawn substructures more than once.

**Expected behavior**
Continue spawning substructures until all the end points spawn in.

**Screenshots**
![Screen Shot 2022-02-21 at 1 44 46 PM](https://user-images.githubusercontent.com/48358224/155017288-1bd1fd33-6add-4085-9a4d-fe2013e2096e.png)

**Environment Information:**
 - Minecraft Version: 1.18.1
 - Spigot Version: paper-1.18.1-197
 - Custom Structures Version: 1.7.1.1
 - World Edit Version: 7.2.8

**Additional context**

**Comment by ryandw11** [comment]
I limit the amount of sub-schematics that can be spawned from each other to prevent infinite recursion. I do think that the number I allow is a little low though so I will change that.

**Comment by KingofAnomaly** [comment]
maybe you can add a way to configure it with a warning?

**Comment by ryandw11** [comment]
That is what I was thinking. A secret way to modify it in the config.
