### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by BobtheBob123456** [ryandw11/CustomStructures#135]
**Describe the bug**
So I wanted to create a schematic for a custom structure. So I selected an area with worldedit, then ran the command /cstructure createschem (name). 

**Steps to Reproduce**
1. Switch server version to 1.18.2
2. Use worldedit to select an area
3. Run the command /cstructure createschem (name)

**Expected behavior**
I expected a message saying that the schematic was properly saved, but since this was my first time using this command, I don't really know what was going to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/101293758/159088821-071ee53b-7906-4218-8a2c-ca682e38a2fb.png)
![image](https://user-images.githubusercontent.com/101293758/159089440-633c7e7c-0c98-4fbd-9b91-46d07525b491.png)

**Environment Information:**
 - Minecraft Version: 1.18.2
 - Spigot Version: 1.18.2
 - Custom Structures Version: 1.7.1.1
 - World Edit Version: 7.2.9

**Additional context**
Worldedit also says that it does not fully support our version of bukkit. Maybe that has something to do with it.

**Comment by BobtheBob123456** [comment]
My guess, is that custom structures doesn't fully support 1.18.2

**Comment by BobtheBob123456** [comment]
Hello

**Comment by ryandw11** [comment]
This is an issue with world edit, not custom structures. You need to update your world edit to a version that supports 1.18.2.
