### ISSUE TITLE
Error Onload 1.14.4

### ISSUE THREAD

**Issue by JuliGame** [ryandw11/CustomStructures#141]
**Describe the bug**
Error OnLoad (java.lang.NoClassDefFoundError: org/bukkit/HeightMap).

**Steps to Reproduce**
Create a 1.14.4 spigot server with the plugin.

**Screenshots**
![image](https://user-images.githubusercontent.com/60196802/167986690-ae63e99d-6c84-46ad-bd58-9f694447fa1b.png)

**Environment Information:**
 - Minecraft Version: 1.14.4
 - Spigot Version: 1.14.4 tested on spigot and paper
 - Custom Structures Version: 1.7.1.1
 - World Edit Version: 7.2.10

**Comment by JuliGame** [comment]
This might be fixed in the devs build, but they are compiled in java 16 and old minecraft servers only run up to java 11-12.

**Comment by ryandw11** [comment]
Unfortunately, the next version of Custom Structures will be compiled with Java 16, so support for older versions like 1.14.4 will be dropped.
