### ISSUE TITLE
Schematic subfolders

### ISSUE THREAD

**Issue by KingofAnomaly** [ryandw11/CustomStructures#147]
**Is your feature request related to a problem? Please describe.**
I have too many schematics and often lose track of where they are in the schematics folder.

**Describe the solution you'd like**
The ability to place schematics inside folders within the schematics folder. I would like to be able to make a folder for each structure I have and be able to store all the sub schematics inside and maybe even folders inside the structure's folder.

**Describe alternatives you've considered**
I have tried naming the schematics in a way to kind of imitate as if they were in folders but I have so many that it is hard to tell where one section ends and the other begins. Some example of substructure names for my crater structure are
- crater_meteorite_obsidian_small.schem
- crater_meteorite_obsidian_shulker_small.schem
- crater_meteorite_crying-obsidian_small.schem
- crater_meteorite_crying-obsidian_ancient-debris_small.schem

**Additional context**
I have a lot of structures that use substructures to create different variations of the structure such as different loot inside the center of a meteorite and various different meteorites.

**Comment by ryandw11** [comment]
I haven't tried, but this might already be supported.

Something like this may work:
```yml
schematic: 'crater/meteorite_obsidian_small.schem'
```
If it doesn't work then I'll try to add it before 1.8.1 goes out.

**Comment by KingofAnomaly** [comment]
from what I can tell it says it works but I can't seem to find the file

**Comment by KingofAnomaly** [comment]
nvm it does work I just forgot to make the folders first

**Comment by KingofAnomaly** [comment]
except maybe it doesn't because it seems like the structure can't find the schematic in the folder even when I put in the file's path

**Comment by KingofAnomaly** [comment]
never mind again I just had an issue with the config unrelated to the structure name sorry
