### ISSUE TITLE
SpawnY: '+[X]' unable to generate structure

### ISSUE THREAD

**Issue by MrLaoGe** [ryandw11/CustomStructures#149]
Server：1.18.1
Version：1.8.1

When filling in SpawnY: top structure can be generated normally, but when filling in SpawnY: '+[X]'(E.g：SpawnY: '+[1]'，SpawnY: '[20;30]'), it will not generate structure.

file：

schematic: toro.schem
Chance:
  Number: 3
  OutOf: 500

StructureLocation:
  Worlds:
    - world
  SpawnY: [240;260]
  SpawnYHeightMap: 'WORLD_SURFACE'
  CalculateSpawnFirst: true
  Biome: 
    - frozen_ocean
    - snowy_tundra
    - snowy_plains
    - ice_spikes
  DistanceFromOthers: 500
  spawn_distance:
    x: 50
    z: 50

StructureProperties:
  PlaceAir: false
  randomRotation: true
  ignorePlants: true
  spawnInWater: true
  spawnInLavaLakes: true
  spawnInVoid: false

SubSchematics:
  Enabled: false
  Schematics:
    demo2:
      file: 'demo2.schem'
      PlaceAir: false
      UseRotation: false

StructureLimitations:
  whitelistSpawnBlocks:
    - packed_ice
    - ice
    - water
    - air

    # Can be flat or flat_error.
    mode: flat
    cornerOne:
      x: -5
      z: -5
    cornerTwo:
      x: 5
      z: 5

  replacement_blocks:
    'BEDROCK': 'AIR'

  replacement_blocks_delay: 0

Masks:
  enabled: false
  union_type: 'AND'

  BlockTypeMask:
    - WHITE_WOOL

  NegatedBlockMask:
    - WHITE_WOOL

LootTables:
  CHEST:
    lootTable: 5
  BARREL:
    lootTable: 5

**Comment by ryandw11** [comment]
It looks like you have a `BlockLevelLimit`. This condition is likely never satisfied with the Y values you have defined. You should delete this section from the configuration file:
```yml
 BlockLevelLimit:
    mode: flat
    cornerOne:
      x: -5
      z: -5
    cornerTwo:
      x: 5
      z: 5
```

**Comment by MrLaoGe** [comment]
thanks

**Comment by MrLaoGe** [comment]
> 它看起来像你有一个 `BlockLevelLimit `。 这种情况可能不会满意你已经定义的Y值。 你应该删除这部分从配置文件:
> 
> ```yaml
>  BlockLevelLimit:
>     mode: flat
>     cornerOne:
>       x: -5
>       z: -5
>     cornerTwo:
>       x: 5
>       z: 5
> ```

I tried removing BlockLevelLimit, but still can't generate the structure

**Comment by ryandw11** [comment]
You can try running `/cstruct testspawn {name}` at a location you expect the structure to spawn and see what is preventing it from doing so.

**Comment by MrLaoGe** [comment]
> You can try running `/cstruct testspawn {name}` at a location you expect the structure to spawn and see what is preventing it from doing so.

Good problem solved, thanks for your help!
