### ISSUE TITLE
External Structure Mask

### ISSUE THREAD

**Issue by DoctorJohnSmith** [ryandw11/CustomStructures#159]
Please add the ability to configure structures not to replace existing blocks, via a mask. 

For my use case I would like to configure an underground structure not to replace existing air blocks. If the structure generate into the air, it would cut off and not replace blocks above ground level. The option to specifically apply this to certain sub schematics would also be useful.

**Comment by ryandw11** [comment]
Already implemented by commit https://github.com/ryandw11/CustomStructures/commit/23f6a141858e3f7faed67ba6db06a74e1658af84. This will be in the next version of the plugin (1.9.0).

**Comment by ryandw11** [comment]
Implemented in 1.9.0.
