### ISSUE TITLE
[CustomStructures] A fatal error has occured! / An internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by tr330ne** [ryandw11/CustomStructures#16]
Please help me with this when I write the /cstructure test (structure) command, then "An internal error occurred while attempting to perform this command" appears in the chat, and when I enter the /cs statuja (structure) command, the "Script does not exist: C \ Users \ (user) \ Desktop \ (server) \ plugins \ WorldEdit \ craftscripts \ statuja.js ", before it appeared after entering the command / cstructure test and at the end of the sentence was written test.js (Script does not exist: C \ Users \ (user) \ Desktop \ (server) \ plugins \ WorldEdit \ craftscripts \ test.js). Please help with this :(
1. When I enter /cstructure test statuja (structure): https://imgur.com/edb1mwT
2. When I enter /cs statuja (structure): https://imgur.com/rC7uJxG

![2019-07-24_10 54 08](https://user-images.githubusercontent.com/53233736/61776786-66d75100-ae04-11e9-91ca-d2279c18487d.png)
![2019-07-24_10 54 53](https://user-images.githubusercontent.com/53233736/61776792-6b036e80-ae04-11e9-9c4b-2bcc0e053b38.png)
![2019-07-24_15 41 03](https://user-images.githubusercontent.com/53233736/61794595-2d194100-ae2a-11e9-9fcd-3e05c0f13c77.png)

Config:
configversion: 3
#========================================
#             Custom Structures    
#========================================
#Wiki: https://github.com/ryandw11/CustomStructures/wiki

#Allow Plugins to delete structures at will.
allowDeletion: true

Schematics:
    #Change the name bellow with what you want.
    statuja:
        #The schematic file. Make sure to include the .schem
        Schematic: 'statuja.schem'
        #What biome this a schematic can spawn in. Change to all for all.
        Biome: 'all'
        #The chance option
        Chance:
            #The number that can be picked out of 1000. So if 1 is picked than it spawns.
            Number: 1
            #The number that the ratio is out off.
            OutOf: 1000
        #If the structure can spawn in all worlds.
        AllWorlds: true
        #If the above is false then the worlds it can spawn in:
        AllowedWorlds:
            - world
        #The y cord the structure will spawn on. Use top if you want it to be on the surface.
        SpawnY: top
        #If you want air to be placed. True is air will be placed. False is air won't be placed.
        PlaceAir: true
        #If you want the structure to spawn in water or lava.
        spawnInLiquid: false
        #If the structure should be randomly rotated.
        randomRotation: false
        #Whitelisted blocks that the structure can spawn on. Remove this list if you do not want a whitelist.
        whitelistSpawnBlocks:
            - Grass_block
            - Dirt
            - air
        #List of lootTables for this Schematic, name and weight
        #Weight determines how often it will be chosen out of all the entries in the list.
        LootTables:
            lootTable: 5
![е1е12н2нг3г](https://user-images.githubusercontent.com/53233736/61794963-09a2c600-ae2b-11e9-96a4-fec5e46cb2ca.png)
![262н2гн3г](https://user-images.githubusercontent.com/53233736/61795074-3f47af00-ae2b-11e9-8973-e0e629018b58.png)
![626272727](https://user-images.githubusercontent.com/53233736/61795163-70c07a80-ae2b-11e9-90f8-f707b63b0cb4.png)

**Comment by ryandw11** [comment]
/cs is a worldedit command. use /cstructure. I need to change the help text.

**Comment by ryandw11** [comment]
Also does file `statuja.schem` exist in the schematics folder. Also can I see the errors from the console?

**Comment by tr330ne** [comment]
> Also does file `statuja.schem` exist in the schematics folder. Also can I see the errors from the console?

Sorry for waiting
[latest.log](https://github.com/ryandw11/CustomStructures/files/3430792/latest.log)

**Comment by tr330ne** [comment]
And I have a couple of questions: 1. How to make the selected mobs spawn in the structure? 2. Is the Illusionist spawn possible? 3. How to properly set the rarity of the structure? For example, once a couple in blocks

**Comment by tr330ne** [comment]
So, I fixed the plugin

**Comment by ryandw11** [comment]
Do you still have those questions?
