### ISSUE TITLE
 How to add spawns of your mobs in Dungee without spawners? (By type Raiders Tower)

### ISSUE THREAD

**Issue by tr330ne** [ryandw11/CustomStructures#17]
How to add spawns of your mobs in Dungee without spawners? (By type Raiders Tower)?
I hope you will help me

**Comment by ryandw11** [comment]
In your schematic put down a sign that says
```
[mob]
{your_mob_name}
```

**Comment by tr330ne** [comment]
And it will work with rotate?  And how to make the mob spawn inside the building and not on the roof (if it is)?

**Comment by ryandw11** [comment]
No it will not work with rotate. That is a bug I am trying to sort out right now. Just put the sign inside the building. It will spawn there. (The sign disappears when the structure is spawned.

**Comment by TreeOnemc** [comment]
Sign with the text:

[mob]
{illusioner}

?

**Comment by tr330ne** [comment]
Okay thanks
