### ISSUE TITLE
Unable to detect minecraft version

### ISSUE THREAD

**Issue by N3xKxp3rrra** [ryandw11/CustomStructures#174]
**Describe the bug**
its trying to enable and says: [23:45:38 ERROR]: [CustomStructures] Unable to detect Minecraft version! The plugin will now be disabled.

**Structure File(s)**
https://pastebin.com/Pku8VexK

**Environment Information:**
 - Minecraft Version: 1.20.6
 - Spigot Version: im not using spigot. im using Purpur (fork of paper)
 - Custom Structures Version: v.1.9.0.1
 - World Edit Version: 7.3.3

**Comment by ghost** [comment]
same error here using bukkit at the same versions of your environments, world edit,  minecraft 1.20.6

**Comment by ryandw11** [comment]
> same error here using bukkit at the same versions of your environments, world edit, minecraft 1.20.6

You're using Bukkit? This issue should only affect paper and its related forks. Either way I should have a fix for this soon.

**Comment by ghost** [comment]
Sorry, i meant PaperMC, not bukkit

**Comment by ryandw11** [comment]
Fixed by commit 03fde42.
