### ISSUE TITLE
Plugin disabled in minecraft server

### ISSUE THREAD

**Issue by asukashi** [ryandw11/CustomStructures#177]
i dont know if this is the right way to ask for a help its my first time doing it and i saw the problem before are somehow related with my problem.

i tried installing advanced enchantment plugin in my minecraft server but it keeps on disabling it this error keep on showing up "[AdvancedEnchantments] Disabling AdvancedEnchantments v9.10.2" can someone help me figure out this. ive tried for 3 straight days but nothing works...i have asked both my hosting and the plugins moderator but both of them cant seem to figure it out.

https://pastebin.com/87thEg3z here is my server latest log

i have tried installing the plugin 1 by 1 but the moment i inserted a second plugin it just disabled the advanced enchantment without any clear error message

**Comment by ryandw11** [comment]
Hey there, I do not have anything to do with AdvancedEnchantments. Try asking for help through the channels provided on their plugin page.
