### ISSUE TITLE
Structure Not Spawning and Causing Errors | Paper 1.14.4 |

### ISSUE THREAD

**Issue by diomonder** [ryandw11/CustomStructures#18]
**Server Jar: Paper
Server Version: 1.14.3
Plugin Version: 1.4.2
World Type: Flat**

Plugin installs fine, I went through the documentation and setup everything to my knowledge properly. The only thing I didnt do was mess with the loot table which I plan on doing when my other server dev gets online.

So I make the schematic with world edit, moved it to the /customstructures/schematics
Setup the config here: https://pastebin.com/BpaWsd07
Like I said the loot table is default from what the plugin comes with.

/cstructures list shows that **"Dungeon01"** is in fact active and registered.
/cstructures test Dungeon01 causes the error giving me this in the console: https://pastebin.com/Y9nKh43w

**Comment by diomonder** [comment]
Fixed, moving the plugin version down one fixed the issue.

**Comment by ryandw11** [comment]
This is clearly a bug that needs to fixed.

**Comment by ryandw11** [comment]
Discovered the bug. Will be patched in 1.4.2.1
