### ISSUE TITLE
Plugin disables on server start

### ISSUE THREAD

**Issue by ShayminPlays** [ryandw11/CustomStructures#21]
I'm using version 1.4.2.1 on Minecraft 1.12.2 running with WorldEdit 7.0.0. Using Spigot
![image](https://user-images.githubusercontent.com/53405165/62009963-bc8d5f80-b15c-11e9-8249-4e32a822203a.png)

I've installed both plugins to my server.pro server and looked at a thread with a similar issue to mine but can't find a solution.

**Comment by ryandw11** [comment]
You need a schematic file. The plugin cannot find the schematic within it's schematic folder. (You need to move the schematic from the world guard folder to inside the custom structures schematic folder.

**Comment by ShayminPlays** [comment]
I created a file called demo.schem and that got the plugin working. Now how do I create a schematic?

**Comment by ryandw11** [comment]
No. You don't create a file. You copy something using world edit and do //schem save demo. That file will cause massive errors with the plugin.

**Comment by ShayminPlays** [comment]
I just deleted that demo.schem folder I created and made a new test schematic called E.schem and restarted the server. Now the plugin doesn't work. Why not?

**Comment by ryandw11** [comment]
Did you change the name of the schematic file in the config.yml

**Comment by ryandw11** [comment]
Due to inactivity I am going to assume this is resolved. If not please open another issue.
