### ISSUE TITLE
Schematics wont load in, Instructions are a bit unclear

### ISSUE THREAD

**Issue by Ligua999** [ryandw11/CustomStructures#24]
So, I made a schematic, I put it in the folder, edited the config file, but the structures generated partially underground, does the structure generate from the pos1? 

When i type any of the commands it gives me an error: script does not exist?

Is there an email or a way I can contact you for further support like discord?

**Comment by ryandw11** [comment]
The structure generates from where you did //copy. The command is /cstructure. /cs is a world edit command.

**Comment by Ligua999** [comment]
> The structure generates from where you did //copy. The command is /cstructure. /cs is a world edit command.

Is the plugin compatible with structure void?

**Comment by ryandw11** [comment]
No it is not. However you can save air spaces with the plugin.

**Comment by ryandw11** [comment]
Improved instructions in 1.4.3
