### ISSUE TITLE
Can't get the plugin to work with 1.14.4

### ISSUE THREAD

**Issue by vasilDerilov** [ryandw11/CustomStructures#25]
All it displays is 'An internal error occurred while trying to execute this command' every time I try to use any command related to the plugin.

**Comment by vasilDerilov** [comment]
Okay I cleared the config and see what you meant when you said you have to reconfigure the config but I still dont know how so will keep trying, for now at least the commands work.

**Comment by ryandw11** [comment]
Can I see your console errors and config. I will need that to determine what is wrong.

**Comment by SenaminBunne** [comment]
Hey I'm experiencing the same error, checked the console and all it says is... 
<img width="591" alt="Screen Shot 2019-09-07 at 10 29 23 PM" src="https://user-images.githubusercontent.com/55039607/64482435-f2901b80-d1bf-11e9-92e9-6f6b4c3a6c25.png">

**Comment by ryandw11** [comment]
That is because the plugin is disabled. The plugin is likely disabled due to a configuration error. If you look the the console log there will be a warning telling you why.

**Comment by Boson04** [comment]
Hey thanks for the suggestion, I have it configured but it still says I don't have a schematic in the folder even though I do and I have it set to load that schematic
<img width="662" alt="Screen Shot 2019-09-08 at 11 58 10 AM" src="https://user-images.githubusercontent.com/55039607/64490930-41759980-d230-11e9-81e9-6dd7a5eed453.png">
<img width="1277" alt="Screen Shot 2019-09-08 at 12 01 31 PM" src="https://user-images.githubusercontent.com/55039607/64490946-7e419080-d230-11e9-9282-c421fcaeaea7.png">
<img width="574" alt="Screen Shot 2019-09-08 at 12 01 50 PM" src="https://user-images.githubusercontent.com/55039607/64490947-7f72bd80-d230-11e9-9395-24042d136d00.png">

I love the idea of this plugin, sorry if its just some silly mistake.

**Comment by SenaminBunne** [comment]
I checked in the console after configuring it and it still says fatal error when I try to test it,
here's my console, my schematic folder and my config.

<img width="662" alt="Screen Shot 2019-09-08 at 11 58 10 AM" src="https://user-images.githubusercontent.com/55039607/64491116-52270f00-d232-11e9-8e0a-4b19316d1e84.png">
<img width="1277" alt="Screen Shot 2019-09-08 at 12 01 31 PM" src="https://user-images.githubusercontent.com/55039607/64491117-52bfa580-d232-11e9-9a7b-cccbb5777613.png">
<img width="574" alt="Screen Shot 2019-09-08 at 12 01 50 PM" src="https://user-images.githubusercontent.com/55039607/64491118-52bfa580-d232-11e9-8fa1-bfe6ce45e3eb.png">

**Comment by ryandw11** [comment]
What version of the plugin are you running. Also can I get the full text of the error along with the config?

**Comment by Onyxtite** [comment]
@ryandw11 I figured out the problem, it happens when you try to load an schematic that doesn't exist (via the test command ). That returns a nullpointer if i remember correctly, and the plugin stops responding, and therefore starts giving "An internal error occurred while trying to execute this command" error any time you try to do a command and stops generating structures. 

Other than that and a separate issue I'll make soon, it runs fine on 1.14.4 paper.

**Comment by memehacks64** [comment]
i have whis erro and the plugin is disable.
![image](https://user-images.githubusercontent.com/21993804/77045327-93893b80-6986-11ea-8331-466885ee1945.png)

**Comment by ryandw11** [comment]
> i have whis erro and the plugin is disable.
> ![image](https://user-images.githubusercontent.com/21993804/77045327-93893b80-6986-11ea-8331-466885ee1945.png)

If you look at the top of the console it will tell you why the plugin is disable. It is likely due to an incorrect configuration.

**Comment by ryandw11** [comment]
Added better error handling in 1.4.3. If help is still needed than please open another issue.
