### ISSUE TITLE
random rotation messes up chests

### ISSUE THREAD

**Issue by PhanaticD** [ryandw11/CustomStructures#26]
unless a schematic is perfectly centered on a square for z/x axis chests and signs can have the potential to be missed. This is due to the fact the code to check for the clipboard region does not respect rotation. I spent forever trying to debug it, and ended up finding this out

should be easy to re-create, just have a long rectangle schematic, and put a chest on one end, and you stand on the other end when saving the schematic. load in a world with it randomly rotated, and the chest will not have any loot from loot tables (or sign replaced with mob) (unless 0 rotation)

**Comment by ryandw11** [comment]
This is a known issue that I am still working on. No ETA is currently available when a fix will come out.

**Comment by ryandw11** [comment]
Fixed in 1.4.3.1
