### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by DarthJecky** [ryandw11/CustomStructures#27]
My server crashes when I load new chunks.
 I'm running Paper build 209 for 1.14.4 with the latest version of Custom Structures and WorldEdit 7.0.0.

**Comment by ryandw11** [comment]
Can I see the crash log?

**Comment by DarthJecky** [comment]
My crash-reports folder is empty and I don't get any errors in the console. It only says that the server stopped.

**Comment by ryandw11** [comment]
It just says the server stopped? Usually there is a crash log or something.

**Comment by ryandw11** [comment]
Inactivity and version is out of date. If the issue persists on 1.4.3 then please open another bug report.
