### ISSUE TITLE
Attempting to get structures to generate in the Nether.

### ISSUE THREAD

**Issue by benrobson** [ryandw11/CustomStructures#30]
Hey,
Love the plugin, still getting my head around how it all works. I have been working with attempting to generate structures in the lava lakes in the Nether. 
My overall result is that even if I change the Y cord to whatever, it always generates on the bedrock surface on the top of the Nether.

**Comment by ryandw11** [comment]
Interesting. I never thought to test the plugin in the nether. I will look into what the issue is.
