### ISSUE TITLE
Estimation of next update.

### ISSUE THREAD

**Issue by benrobson** [ryandw11/CustomStructures#31]
Hello ryandw11,
I am an Administrator and Head of Development for an upcoming Minecraft Server and I am looking to see when another update is coming to CustomStuctures.
Our server is going to have an SMP aspect to it and we have gotten our community to submit a bunch of builds which we have chosen to generate in the Servers world.
We are wanting to use your CustomStuctures plugin in our Server.

We would be willing to beta test whatever you have and give you feedback.
We are wanting to release our Server sometime in December.

**Comment by ryandw11** [comment]
Thank you for being willing to test the plugin; however, I think I can handle it currently. If everything goes right I hope to release the plugin later today.

**Comment by benrobson** [comment]
Hey ryandw11,
Just following up on this issue from a little while ago, is there a update of CustomStructures that could be tested?
I saw that in a recent commit you're working towards spawning structures at the bottom of the ocean. Is that completed or still in testing?

**Comment by ryandw11** [comment]
Sorry for the very late response. I think I am done with the spawning. I will just need to double check.

**Comment by MCHalfAssed** [comment]
Hey! Just wanted you to know that I am also looking forward to your next update for this plugin. 
Thanks for making it! :)

**Comment by Nanogamer7** [comment]
Any news so far? Are you sure you don’t want free QA/bug testing? :p
Joke aside, I’m really looking forward to a 1.15 compatible version, as I’m too planning a small server now that OptiFine 1.15 is soon to be released.
Thank you

**Comment by ryandw11** [comment]
1.4.3 is complete. Sorry for the long wait.
