### ISSUE TITLE
MythicMobs not spawning

### ISSUE THREAD

**Issue by VyrussGG** [ryandw11/CustomStructures#32]
So essentially after putting the signs down and testing the structure, the sign will disappear but no mob will spawn. Attached are screenshots of both in game and the config of MythicMobs.

![](https://i.imgur.com/BO7vtck.png)

![](https://i.imgur.com/lkMqG1g.png)

On a side note, vanilla mob spawning is working fine, so it's only happening with Mythic Mobs. I also know that the Mythic Mob is spawning fine on its own as well, so there isn't an error in that code either.

**Comment by ryandw11** [comment]
Fixed in 1.4.3.1
