### ISSUE TITLE
SpawnY goes above specified Y level

### ISSUE THREAD

**Issue by MarcussGTX** [ryandw11/CustomStructures#33]
When specifying that the structure can spawn between 100-200, it spawns above this level and even attempts to spawn above 255 resulting in error in console.

Config:

configversion: 3
#========================================
#             Custom Structures    
#========================================
#Wiki: https://github.com/ryandw11/CustomStructures/wiki

#Allow Plugins to delete structures at will.
allowDeletion: true

Schematics:
    #Change the name bellow with what you want.
    phantom-floater:
        #The schematic file. Make sure to include the .schem
        Schematic: 'phantom-floater.schem'
        #What biome this a schematic can spawn in. Change to all for all.
        Biome: 'all'
        #The chance option
        Chance:
            #The number that can be picked out of 1000. So if 1 is picked than it spawns.
            Number: 1
            #The number that the ratio is out off.
            OutOf: 100
        #If the structure can spawn in all worlds.
        AllWorlds: false
        #If the above is false then the worlds it can spawn in:
        AllowedWorlds:
            - world
        #The y cord the structure will spawn on. Use top if you want it to be on the surface.
        SpawnY: [100-200]
        #If you want air to be placed. True is air will be placed. False is air won't be placed.
        PlaceAir: false
        #If you want the structure to spawn in water or lava.
        spawnInLiquid: false
        #If the structure should be randomly rotated.
        randomRotation: true
        #Whitelisted blocks that the structure can spawn on. Remove this list if you do not want a whitelist.
        whitelistSpawnBlocks:
            - Grass_block
            - Dirt
            - Stone
            - air
        #List of lootTables for this Schematic, name and weight
        #Weight determines how often it will be chosen out of all the entries in the list.
        LootTables:
            lootTable: 5

**Comment by ryandw11** [comment]
can I have a copy of your schematic?

**Comment by ryandw11** [comment]
Patched in 1.4.3. Thank you for the bug report.
