### ISSUE TITLE
Schematics Dont works

### ISSUE THREAD

**Issue by zSkyBlack** [ryandw11/CustomStructures#41]
When I try to create a structure it tells me that the plugin only supports .sj files but I don't understand it can you explain it to me?

**Comment by ryandw11** [comment]
Can I see you config. Also the plugin doesn't support .sj files. It uses .schem files.

**Comment by zSkyBlack** [comment]
Ye, but what config?

**Comment by ryandw11** [comment]
The plugin config. You can find it at `plugins/customstructures/config.yml`

**Comment by zSkyBlack** [comment]
no problem, I can fix i used wrong command sorry.

**Comment by zSkyBlack** [comment]
I used /sc xd i'm idiot thanks for ur attention I like so much ur plugin
