### ISSUE TITLE
Add the option for structures to spawn on lava lakes.

### ISSUE THREAD

**Issue by benrobson** [ryandw11/CustomStructures#42]
I have tried to get this structure to generate on a lava lake by giving the y level of the lava lake and it is  still not generating correctly.
Here is a photo of the result: https://gyazo.com/d51d7b9149bee08fddca8aceba055de9
Here is a text bin of my configuration: https://hastebin.com/adaboyafir.js

**Comment by ryandw11** [comment]
Since the nether is one large biome, there really is no good way for me to find out where the lava lakes are.

**Comment by benrobson** [comment]
You could make it that it performs a radius check to ensure there is lava in the vicinity?

**Comment by ryandw11** [comment]
Your structure must have spawned on lava. I can attempt to check; however, this may impact performance.
