### ISSUE TITLE
Mob Signs don't 100% work.

### ISSUE THREAD

**Issue by benrobson** [ryandw11/CustomStructures#44]
I am looking at spawning mobs via the sign method (https://github.com/ryandw11/CustomStructures/wiki/Mob-Spawning) and while looking into putting this in my structure, it seems that the mob signs work not 100% of the time and aren't really replaced correctly.

This was the initial blueprint:
![image](https://user-images.githubusercontent.com/15405528/78879608-759b8c00-7a97-11ea-82b0-7350beb2c8a7.png)

This is the result in world spawn:
![image](https://user-images.githubusercontent.com/15405528/78880138-4afe0300-7a98-11ea-8b54-1574852678e4.png)

**Comment by ryandw11** [comment]
It is a bug with random rotations. I am still looking into a fix for it, but have been unsuccessful for awhile. I will continue trying to solve this bug.

**Comment by ryandw11** [comment]
Fixed in 1.4.3.1
