### ISSUE TITLE
cna i have a step step guide on how to use this

### ISSUE THREAD

**Issue by loumac321** [ryandw11/CustomStructures#49]
I'm using this on my aternos server and don't know what to do. plz help

**Comment by ryandw11** [comment]
First of all you need a structure to use. Use world edit to select your structure. Fly to where you want the center to be and do //copy. Then do //schem save (name). Take the .schem file from the worldedit folder and put it into the schematics folder in the custom structures plugin.

Open up the config file and configure the demo schematic to your liking. (You can rename it to what ever you want). Then change the `schematic: ''` configuration to use what you named it.

I might make a video to demonstrate this soon.

**Comment by loumac321** [comment]
Do u know how I would do this in my Aternos server?

**Comment by benrobson** [comment]
@loumac321 look at my response on #50
