### ISSUE TITLE
how do I use this with my aternos server

### ISSUE THREAD

**Issue by loumac321** [ryandw11/CustomStructures#50]
I've downloaded it onto my server but I can't put a schematic in the folder please help!

**Comment by ryandw11** [comment]
I have no clue how aternos works. Maybe download the schematic, then upload it back into the correct folder.

**Comment by loumac321** [comment]
if they dont allow to import files will it not work

**Comment by ryandw11** [comment]
If there is no way to move files from the world edit folder to the custom structures folder, then it will not work.

**Comment by KeanBuyst** [comment]
You could download the files from aternos under the world section, then add the schemactics you whant to the correct folder and then re-upload the world.

**Comment by benrobson** [comment]
Unfortunately I don't think you can, after a little research I've found the following: 
> Aternos doesn't offer access via FTP or the ability to upload custom mods/plugins. There are many reasons for this decision but it's mainly for security reasons.
> https://support.aternos.org/hc/en-us/articles/360027235831-Uploading-files-and-FTP-access
