### ISSUE TITLE
Plugin Suggestion

### ISSUE THREAD

**Issue by bmr-ramos** [ryandw11/CustomStructures#51]
Hey, just wanted to say that your plugin is amazing and we are currently using it on our Earth Factions server. I have a suggestion perhaps that could be added in a future update. Is there any way the plugin can be configured so that if it senses a specific flat block by block radius, it will spawn a structure? Like for example, if there is a 15x15 flat block surface of grass blocks, it will spawn a structure. This is to prevent any structures from spawning in the air because it’s target was a mountain.

**Comment by ryandw11** [comment]
I can try to implement something like this. My number one concern though is performance. Also a 15x15 flat area is seriously uncommon, your structure would almost never spawn.

**Comment by ryandw11** [comment]
Added in 1.5
