### ISSUE TITLE
Vanilla Loot Tables?

### ISSUE THREAD

**Issue by Diamondback88** [ryandw11/CustomStructures#55]
Is there a way for the plugin to read vanilla loot tables (AKA the json-style version used in vanilla)?

Additionally, the wiki is updated for future version 1.5 - do you know (ETA) when that's being released?

**Comment by ryandw11** [comment]
No there is no way to do it using the vanilla style. That future version is coming out soon. I have a working prototype and just need to add in a few more features.

**Comment by ryandw11** [comment]
1.5 is released. (Vanilla Loot tables will not be added right now).
