### ISSUE TITLE
Reload Function Broken

### ISSUE THREAD

**Issue by Diamondback88** [ryandw11/CustomStructures#56]
Reload function itself works as intended, but whenever an error occurs, the reload function will spit out an error(https://imgur.com/a/VIPqkNg), and even if you fix the issue after that, the reload function will get stuck on the same error until you restart the server.

**Comment by benrobson** [comment]
What is the error in the console?

**Comment by Diamondback88** [comment]
Essentially, when a schem file is missing, but it was referenced in a structure file, it will throw the standard error message, but it'll keep throwing the standard error message even after you replace the necessary schem file.

**Comment by benrobson** [comment]
Not really asking what happens, asking to see if any error is in the console when it happens. If there is an error throw it in https://hastebin.com/ and paste that link here.

**Comment by ryandw11** [comment]
It is just simply a bug in the code. I think I fixed the issue in the new 1.5 version of the plugin.

**Comment by MariusHBovbjerg** [comment]
I ran into the same issue with the newest version today, on spigot 1.15.2. 
As I'm still developing it's not a big issue, but I can see how it'd pose an issue on a server with people playing.

**Comment by ryandw11** [comment]
Alright, I still hope I patched it on 1.5. I will make sure to do lots of testing on it though to make sure.

**Comment by benrobson** [comment]
Would we be able to test it in another branch somewhere?

**Comment by ryandw11** [comment]
> Would we be able to test it in another branch somewhere?

Yes, it is under the 1.5 branch. You will need to compile it yourself though.
(Keep in mind the migration feature is not implemented yet, so old configurations will not work).

**Comment by benrobson** [comment]
> 
> 
> > Would we be able to test it in another branch somewhere?
> 
> Yes, it is under the 1.5 branch. You will need to compile it yourself though.
> (Keep in mind the migration feature is not implemented yet, so old configurations will not work).

Yeah cool, I can compile myself easily, just generate a new config.
Is the entire project in maven or do I have to manually import everything?

**Comment by ryandw11** [comment]
> Yeah cool, I can compile myself easily, just generate a new config.
> Is the entire project in maven or do I have to manually import everything?

You have to import everything manually. Maven doesn't play nice with multiple spigot versions.

**Comment by ryandw11** [comment]
Most likely fixed in 1.5.
