### ISSUE TITLE
Monsters can not be generated normally

### ISSUE THREAD

**Issue by SheerHuangJin** [ryandw11/CustomStructures#57]
Monsters can not be generated normally, whether it is MM or the original monster
If you use test, it will be generated normally
CustomStructures-1.4.3.1
paper-1.15.2

![Snipaste截图于2020年06月05日05时58分32秒](https://user-images.githubusercontent.com/65820295/83814903-c3c4b880-a6f1-11ea-82fa-833a43f22fed.png)
![Snipaste截图于2020年06月05日05时59分26秒](https://user-images.githubusercontent.com/65820295/83814908-c6271280-a6f1-11ea-8007-e0c5e2e7f7c8.png)

**Comment by ryandw11** [comment]
I'm sorry about the late response, I thought I responded to this.

Basically what is happening is that the mob is spawning in, but then is immediately despawned due to the mob not being in range of a player. I will correct this in the next update.

**Comment by ryandw11** [comment]
Fixed in 1.5
