### ISSUE TITLE
Can I create things like holes on the ground ?

### ISSUE THREAD

**Issue by bouchbi** [ryandw11/CustomStructures#59]
Hi, I would like to know if there is a possibility to tell to the plugin that he must paste a structure in a way that the top is at the surface. I know there is a way to paste it at the ground but is it possible to paste the top of the structure at the ground ? To create like a hole at the surface.
I don't know if you understood because I am french and my idea is kind of hard to explain 😅.
Anyway, thank you,
Have a good day

**Comment by ryandw11** [comment]
Ok so if I understand you correctly you want the top of a structure to be placed at ground level. This can be done in two ways: 
1) When you go to copy the structure with world edit you should stand on top of the structure and do `//copy` then the normal `//schem save {name}`. That will paste the top of the structure at ground level.
2) Your second option is to configure the plugin to paste the structure x blocks below the ground. This can be done by setting the SpawnY value in the structure settings to a negative number. For example, to spawn the structure 5 blocks below the ground you would put `SpawnY: -5`

Hopefully that answers your question.

**Comment by bouchbi** [comment]
Ok, I will try that tommorow. I would tell you if it won’t work.
Thanks for your help 🙏

**Comment by bouchbi** [comment]
Actually I have an other problem 😅.
We want to make a custom cave, the issue is that we want to spawn it underground but keeping the air blocks which are inside the cave but not outside. We have thought of filling the outside with random blocks and apply a filter to get rid of them (example: //copy -m !sponge), and then save the schematic. However, when making this and loading the schematic, it paste air instead of the blocks that we did not want it to paste. This is pretty embarrassing, and I think we may need to apply the filter when doing the //paste (example: //paste -m !sponge), I am just not sure that your plugin can do that 😕

**Comment by ryandw11** [comment]
Current it is not possible, I can look into a way of doing though.

**Comment by bouchbi** [comment]
Thanks, it would be such a good update I think it would help a lot of peoples.
I may have an  idea, one of the way you could do it is by adding in the config an option where we can make a list of blocks that we don't want the plugin to spawn, and this list would be used to create a mask on the //paste command the plugin execute. I don't know if I am clear or if it is a solution but if you can work on it and find a way to do it, it will be awesome 😊

**Comment by ryandw11** [comment]
Added in 1.5
