### ISSUE TITLE
An update on CustomStructures for 1.16.1 and Version 1.5

### ISSUE THREAD

**Issue by ryandw11** [ryandw11/CustomStructures#63]
Minutes ago Spigot released for 1.16.1.

The current version of Custom Structures should work on 1.16.1.

Version 1.5 will support 1.13.2-1.16.1. Version 1.5 is extremely close to coming out. 

Only a few more features need to be done. I am going to put an ETA for CustomStructures on June 27, 2020. 
Remember that the ETA is for my goal only. I will not release 1.5 if the plugin is buggy.
## Testing 1.5
Want to help test 1.5?
You can by cloning the 1.5 branch on github. You will need to compile the code yourself for now. I might post a pre-compiled jar on here. The wiki is updated with all 1.5 information including the conversion process.

**Comment by benrobson** [comment]
Thankful for your project and the work you put into it, looking forward to release and testing this.

**Comment by ryandw11** [comment]
1.5 Release Candidate One is now out.
https://github.com/ryandw11/CustomStructures/releases/tag/1.5-RC1

**Comment by ryandw11** [comment]
1.5 has been released
