### ISSUE TITLE
(Question) Can you create custom items in a loot table using a custom item plugin?

### ISSUE THREAD

**Issue by KeanBuyst** [ryandw11/CustomStructures#64]
I have been making custom items on this plugin and I was wondering if you could use them in the loot tables?

Here is link to plugin if you need it: https://dev.bukkit.org/projects/custom-items-and-textures

**Comment by ryandw11** [comment]
I have plans to implement this in the next update. Thanks for the link to the plugin, I will use it in testing the plugin.

**Comment by ryandw11** [comment]
Added in 1.5
