### ISSUE TITLE
 Mobs do not spawn through tablets

### ISSUE THREAD

**Issue by TreeOne31** [ryandw11/CustomStructures#65]
For some reason, mobs will not spawn on the place of the tablets where I write [mob] and the name of the mob is below, after generating the structure, the tablet for some reason remains empty and no mob is spawned in its place
![2020-06-26_13 52 07](https://user-images.githubusercontent.com/67464568/85850489-8e256380-b7b5-11ea-88ff-7d58b671d50f.png)

**Comment by ryandw11** [comment]
What version of world edit are you using? It looks like sign data is not being stored.

**Comment by TreeOne31** [comment]
> What version of world edit are you using? It looks like sign data is not being stored.

I use WorldEdit Bukkit Plugin 7.2.0 Beta 1 (1.13.2-1.16.1), is it necessary to use only WorldEdit mod in singleplayer?

**Comment by ryandw11** [comment]
No, only the plugin is supported. Do //paste {schemname} and check to see if the sign has any text on it.

**Comment by TreeOne31** [comment]
> No, only the plugin is supported. Do //paste {schemname} and check to see if the sign has any text on it.


Sorry for the long reply. No, the inscription is not saved after paste, so this is a problem in WorldEdit, thanks for the help
