### ISSUE TITLE
Wrong probability algorithm

### ISSUE THREAD

**Issue by Fish-In-A-Suit** [ryandw11/CustomStructures#67]
First of all, sincere thanks for updating the plugin, it really means a lot!

However, I have spotted a bug in the way probability for the structure spawning is handled, in comparison to the previous algorithm. With the new algorithm, the structures spawn much less frequently than with the previous algorithm. Let's analyse it!

Each Structure class has a `canSpawn` method, which goes through all of the spawning limitations for that structure. One of those is also the probability check. Here, two numbers are important: **chanceNumber** and **chanceOutOf**. Now, this is the algorithm.

![image](https://user-images.githubusercontent.com/37004357/86120472-aa3a4500-bad4-11ea-9c6b-1f8feef316d3.png)

It works by picking a random integer between `chanceNumber `and `chanceOutOf `. Then, if the random integer is not equal to `chanceNumber`, a false value is returned, meaning the structure cannot be spawned. Let's try it with some example numbers. Let's suppose the `chanceNumber = 9` and `chanceOutOf = 10`; if we put this to words, it should mean that the structure should be spawned in roughly 9 out of every 10 chunks. However, if we were to take a look at the values returned by ThreadLocalRandom.current().nextInt(9, 10) when the number of generated numbers approaches infinity, we'd see that 9 and 10 are returned roughly equally, that there is roughly 50% cases when 9 is returned and 50 cases when 10 is returned. Because of that, we get only 50% probability when specifying 9 out of 10 (I would assume we want 90% probability with that).

My solution is to generate a random integer between 0 and `chanceOutOf`, and then check if the random integer is greater than the `chanceNumber`:

`if(ThreadLocalRandom.current().nextInt(1, getChanceOutOf()+1) > chanceNumber) { //false }`

_Note: ThreadLocalRandom.nextInt(origin, bound): Returns a pseudorandom int value between the specified origin (inclusive) and the specified bound (exclusive). Must be taken into account!_

Let's try the above example with this solution: `chanceNumber = 9` and `chanceOutOf = 10`. A random value between 0 and 10 is generated, and this value is then checked if it is greater than 9, which happens in roughly 10% of the cases. So 10% of the attempts return a false value, and in 90% attempts the algorithm for checking other spawn conditions proceeds past the probability check.

I hope I made myself at least a bit clear with where I am aiming. Thank you for developing this plugin once again!

**Comment by ryandw11** [comment]
You're right, that is not the intended result. The algorithm itself has not changed though, this bug has always been in the plugin since the beginning.
