### ISSUE TITLE
Bug in BlockLevelLimit.isEnabled

### ISSUE THREAD

**Issue by Fish-In-A-Suit** [ryandw11/CustomStructures#68]
I've found one more bug in the BlockLevelLimit class.

Each Structure has one instance of BlockLevelLimit class. In the `canSpawn()` method of the `Structure`, it is checked whether the `BlockLevelLimit `is enabled for that structure. If it is not enabled, the mode will is set to `"NONE"`. The problem is that the existing method public boolean isEnabled() { return mode.equalsIgnoreCase("none") }; returns true when the mode is none (should be false)

Simple solution is done with negation: 

![image](https://user-images.githubusercontent.com/37004357/86129870-a3ff9500-bae3-11ea-839e-d54a8b7b0bce.png)

**Comment by ryandw11** [comment]
Thanks for catching that!
