### ISSUE TITLE
Does it work with /wb fill?

### ISSUE THREAD

**Issue by Fish-In-A-Suit** [ryandw11/CustomStructures#69]
Hello ryand!

I am trying to integrate your plugin along with the /wb fill command, but I am getting some weird command logs, saying that schematic pasting was terminated for the safety of the server.

Do you possibly know whether the plugin is compatible with the wb fill command?

This is the log. As you can see, execution works, fine, but then those errors occur :(
![image](https://user-images.githubusercontent.com/37004357/86920943-b81e4480-c12a-11ea-93cd-4409933ac217.png)

**Comment by ryandw11** [comment]
It looks like you have debug mode enabled yet the error is not showing. I'll look into this some more.

**Comment by ryandw11** [comment]
I'm going to mark this as outdated. If the issue still persists please reopen an issue.
