### ISSUE TITLE
Is it possible to add support to Itemsadder Plugin?

### ISSUE THREAD

**Issue by FourRumble7698** [ryandw11/CustomStructures#71]
Recently I bought the plugin "Itemsadder" It adds new blocks and Items. The author of this plugin created an extension of the worldedit that supports these custom blocks. The schematics with the worldedit extensions work perfectly with the custom blocks. But when I try to generate the schematic in the folder of custom structures. It can't generate properly.

I use these plugins:
- worldedit-bukkit-7.2.0-beta-02
- Itemsadder: https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-itemsadder%E2%9C%A8-custom-items-huds-guis-textures-3dmodels-emojis-blocks-wings-hats.73355/
- World edit (Itemsadder extension): https://www.spigotmc.org/resources/addon-itemsadder-worldedit.79012/

**Comment by ryandw11** [comment]
This plugin uses the worldedit api to generate the structures. Try saving the structure with the world edit command and moving the schematic from the worldedit folder into the customstructures folder.

**Comment by FourRumble7698** [comment]
Yes It works!. It was a mistake of me. and sorry for answer this late. Thanks for your support!

**Comment by ryandw11** [comment]
Awesome.

**Comment by xalixilax** [comment]
Hello i would like to reopen this issue. I've been using ItemsAdder and i can generate structure without any issue, but the structure blocks is not registering anything into ItemsAdder. So when i break a block, nothing drop. I can also make the texture change if I update the block.
I'm using all all updated plugins FourRumble used at the time. I can load and paste a schematic using world edit without any issue but when i drag and add it to customStructure, it dosn't work anymore.
