### ISSUE TITLE
mythic mobs mobs and mob spawners aren't included in random spawning structures

### ISSUE THREAD

**Issue by soupcoup** [ryandw11/CustomStructures#72]
i made a dungeon with mythic mobs and spawners for mobs and i cant get it to spawn in the world with the mobs and the mob spawners

**Comment by ryandw11** [comment]
Can you share screenshots of what the original dungeon and the spawned dungeon looks like?

**Comment by soupcoup** [comment]
It looks the same but without mythic mobs spawners or the mobs

**Comment by ryandw11** [comment]
Does it spawn the mobs when you do `/cstructure test [name]`?

**Comment by soupcoup** [comment]
Thet dont

**Comment by soupcoup** [comment]
They dont*

**Comment by ryandw11** [comment]
Are there empty signs when you run `/cstructure test`?

**Comment by soupcoup** [comment]
I havent checked but I will when I hop on the server
