### ISSUE TITLE
Do structures generate as chunks are first loaded in, or do you run a command to spawn them?

### ISSUE THREAD

**Issue by nnzo** [ryandw11/CustomStructures#73]
Sorry, this isn't really an issue, just a question.

How does structures generate? Do they generate as chunks are first loaded into the world or do you have to run a command to populate the world with them?

Thanks in advance :)

**Comment by ryandw11** [comment]
Structures are generated into the world when a new chunk is created (as long as the structures are allowed to spawn in that world). Another thing to note is that structures will never generate within the spawn chunks of a world.

**Comment by nnzo** [comment]
Awesome! This is what I wanted to know :)
