### ISSUE TITLE
replacement_blocks feature does not work

### ISSUE THREAD

**Issue by WarWolf-1** [ryandw11/CustomStructures#74]
**Describe the bug**
I'm unable to replace certain blocks in structures with replacement_blocks feature.

**Steps to Reproduce**
add 
  replacement_blocks:
    'WHITE_WOOL': 'AIR'
under StructureLimitations section
**Expected behavior**
white wool should be replaced with air. this is not limited to white wool.

**Environment Information:**
 - Minecraft Version: 1.16.3
 - Spigot Version: git-Paper-191
 - Custom Structures Version: 1.5.2
 - World Edit Version: 7.2.0 snapshot 5350

**Comment by ryandw11** [comment]
I will look into this.

**Comment by ryandw11** [comment]
I can't seem to reproduce this issue. Replacing WHITE_WOOL with AIR works fine for me.

**Comment by WarWolf-1** [comment]
Can you give me your structure config?

**Comment by WarWolf-1** [comment]
Weird thing is that i can replace air blocks, but not anything else

**Comment by ryandw11** [comment]
Do you use world edit or something like FAWE?

**Comment by WarWolf-1** [comment]
just regular awe

**Comment by ryandw11** [comment]
AWE does not paste schematics immediately, which means that it tries to replace the blocks before the structure is spawned in by AWE. To fix this you must adjust the replacement block delay time. Setting it to something like 2 seconds should be enough. `/cstructure test` is affected by the delay so you can use that command to adjust the settings. Additional information on that setting can be found here: https://github.com/ryandw11/CustomStructures/wiki/Structure-Formatting#replacement-blocks-delay

**Comment by WarWolf-1** [comment]
sorry for the late reply. Works after setting a delay
