### ISSUE TITLE
Structures spawning below ground

### ISSUE THREAD

**Issue by Burnt4023** [ryandw11/CustomStructures#75]
I've set a structure's SpawnY to "top", but it spawns a few blocks below ground.

Simply create a structure and set it's SpawnY to top.

It expected the structure to actually spawn above ground, not afew blocks below it.

**Screenshots**
https://imgur.com/a/i4HDdgW

**Structure File(s)**
https://pastebin.com/jBwQ7qbP

**Environment Information:**
 - Minecraft Version: 1.16.3
 - Spigot Version: paperspigot-193
 - Custom Structures Version: 1.5.3.1
 - World Edit Version: 7.2.0

**Comment by ryandw11** [comment]
Where did you do //copy or /cstructure createSchem from? The structure will spawn based upon where you stood when you created it.

**Comment by Burnt4023** [comment]
I tried copying both right next to the structure and about 10 blocks above it, but the issue was still the same.

**Comment by ryandw11** [comment]
When you do `/cstructure test` where does it spawn?

**Comment by Burnt4023** [comment]
Still below ground.

**Comment by ryandw11** [comment]
That means the //copy location is where you stood for /cstructure test.
