### ISSUE TITLE
Trying to create a new schematic in game with worldedit, after entering the command it just shows me the cstructure help

### ISSUE THREAD

**Issue by cmm-66** [ryandw11/CustomStructures#77]
I am using the 1.12.2 special version if that helps, I'm testing out the commands on a test structure and it isn't functioning.
I've typed in /cstructure createschem testname and it just shows me the results as if I typed in /cstructure with no other args

**Comment by ryandw11** [comment]
The 1.12.2 version does not contain that command. I might look into adding support for 1.12 in the main version though.

**Comment by cmm-66** [comment]
oh ok, so do I have to edit the ymls directly in order to add stuff?

**Comment by ryandw11** [comment]
As of right now you do.
