### ISSUE TITLE
Add support for Citizens2

### ISSUE THREAD

**Issue by fgulde** [ryandw11/CustomStructures#79]
Hey,
I'm making an RPG Server and it would be so great if there would be a feature to spawn NPCs in Structures with custom Commands from CitizensCMD. 
With that feature you could make preconfigured quests and make a never seen before RPG feeling.
A feature that you can configure with what chance and where in the structure they spawn would be so great!

**Comment by ryandw11** [comment]
I could look into the citizens api.
