### ISSUE TITLE
Generate chests with loot tables.

### ISSUE THREAD

**Issue by TheRedMajora** [ryandw11/CustomStructures#8]
Any chance to add chests with set loot tables?
If possible, it will check the contents of the chest in the schematic file and then fill the chest with a loot table configured for the item in the chest?
Example: You put a diamond in the chest of the schematic and then the plugin loads a "diamond_loot_table" file and fills the chest with said loot?

**Comment by ryandw11** [comment]
It's a good idea I have tried to implement many times, however I have stopped development on this plugin until the world edit api stops updating so I can work on it without the api changing on me.

**Comment by TheRedMajora** [comment]
Ahh, that’s fair!
Would you mind if I compiled my own version of your plugin for my server?
- If I get chest generation working I’ll be happy to share my code

**Comment by ryandw11** [comment]
Go ahead. This project is open source.
