### ISSUE TITLE
1.12.2 doesnt work

### ISSUE THREAD

**Issue by JeffsHer** [ryandw11/CustomStructures#81]
**Describe the bug**
1.12.2 doesnt work

**Steps to Reproduce**
just run the special edition with world edit in 1.12.2

**Expected behavior**
should work

**Screenshots**
error logs
[04:15:56 ERROR]: [CustomStructures] Error: The schematic file for demo does not exist!
[04:15:56 ERROR]: [CustomStructures] Please put that file in the Schematics folder!
[04:15:56 ERROR]: [CustomStructures] For assistance please contact Ryandw11 on spigot.

**Structure File(s)**
Please put any related structure files in a pastebin (https://pastebin.com/) and provide a link.

**Environment Information:**
 - Minecraft Version: 1.12.2
 - Spigot Version:
 - Custom Structures Version:special version 1.11-1.12
 - World Edit Version: 6.1.9

**Additional context**
please respond

**Comment by ryandw11** [comment]
The plugin cannot find the `demo.schem` file within the schematics folder. Does `demo.schem` exist?

**Comment by JeffsHer** [comment]
yes all i did is download the source code and plugin and used the files in the source code

**Comment by JeffsHer** [comment]
> 
> 
> The plugin cannot find the `demo.schem` file within the schematics folder. Does `demo.schem` exist?

yes
if you mean by demo.schematic

**Comment by ryandw11** [comment]
Can I see your config?
