### ISSUE TITLE
Issue With Loot Tables

### ISSUE THREAD

**Issue by Zanforian** [ryandw11/CustomStructures#82]
I tried adding another loot table beside the default by just copying the loot table and changing the necessary fields, but when I tried to link the table to my structure it causes internal errors and completely disables the plugin. I have no idea what went wrong. The custom items seem to be fine as I can summon them with the getitem command.

Structure:
https://pastebin.com/1eqv38TQ
Loot Table:
https://pastebin.com/46kjra0m
Console:
https://pastebin.com/CXVUTJRz

**Comment by ryandw11** [comment]
`WATTER_BOTTLE` is not a valid material type. Currently there is not way to add a water bottle; however, I can add a way of doing it.

**Comment by Zanforian** [comment]
Huh, your right. Minecraft considers water bottles to be potions for some reason. I just added it as a custom item for now. Thank you.

**Comment by ryandw11** [comment]
I am just going to leave the custom item solution.
