### ISSUE TITLE
problem with stairs

### ISSUE THREAD

**Issue by JeffsHer** [ryandw11/CustomStructures#85]
**Describe the bug**
the stairs arent replicated as well so if its upside down it will still end up in the same direction

**Steps to Reproduce**
just make a schematic using stairs

**Expected behavior**
should face the right direction

**Screenshots**
no

**Structure File(s)**
Please put any related structure files in a pastebin (https://pastebin.com/) and provide a link.

**Environment Information:**
 - Minecraft Version: 1.16.1
 - Spigot Version: 
 - Custom Structures Version: 1.16.1
 - World Edit Version: 7.1.0

**Additional context**

**Comment by ryandw11** [comment]
This sounds like a world edit problem. Try //copy and //paste with worldedit to see if the issue still occurs.

**Comment by ryandw11** [comment]
I'm am going to assume that this issue has been resolved.
