### ISSUE TITLE
spawning structures with mobs doesnt work

### ISSUE THREAD

**Issue by JeffsHer** [ryandw11/CustomStructures#86]
**Describe the bug*
you cant include mobs to what you are spawning

**Steps to Reproduce**
make a schematic and summon some mobs inside the area of the schematic

**Expected behavior**
mobs should spawn at the schem

**Screenshots**

**Structure File(s)**
Please put any related structure files in a pastebin (https://pastebin.com/) and provide a link.

**Environment Information:**
 - Minecraft Version:1.16.1
 - Spigot Version:
 - Custom Structures Version:1.16.1
 - World Edit Version: 7.1.0

**Additional context**

**Comment by ryandw11** [comment]
Did you add the mobs before or after making the schematic?

**Comment by JeffsHer** [comment]
before
i spawned a few zombies and created the schematic

**Comment by ryandw11** [comment]
This also sounds like a world edit issue. Try updating your worldedit.
