### ISSUE TITLE
how do you include mobs to your random structures?

### ISSUE THREAD

**Issue by JeffsHer** [ryandw11/CustomStructures#87]
i want to know how to include mobs to my random structure cause you cant copy mobs (idk is a bug probs) so is there any way to spawn structures with mobs included??

**Comment by ryandw11** [comment]
Yes there is. See this page here: https://github.com/ryandw11/CustomStructures/wiki/Mob-Spawning

**Comment by JeffsHer** [comment]
rip im on 1.16.1

**Comment by ryandw11** [comment]
Oh that notice is outdated. That was back when 1.16 first released and world edit didn't support it yet. As long as you have the latest version of worldedit that supports 1.16 then it will work.
