### ISSUE TITLE
is there plans for 1.14?

### ISSUE THREAD

**Issue by Mrs-Feathers** [ryandw11/CustomStructures#9]
i love this plugin but will there be an update for 1.14?

**Comment by ryandw11** [comment]
Yes, there will be a 1.14 update. Waiting for some free time to update it and world edit to update.

**Comment by Mrs-Feathers** [comment]
awesome! [btw worldedit latest builds work on 1.14, they've been in beta since like 1.12.X, so no real use waiting for a non-beta update, i guess.] i'm super excited and have loads of ideas for structures [saved with the datablocks in vanilla minecraft for vanilla custom structures.. trying to see if i can't make them spawn in specific biomes. like... tree house has a chance to randomly spawn in jungle and a small cottage has a chance to spawn in praries.]

**Comment by ryandw11** [comment]
As of currently you can't load schematics using data blocks. They need to be made using world edit. Also thanks for the information about world edit. I'll look into the api changes and update it.

**Comment by Mrs-Feathers** [comment]
Ah ok. Idk how it works in 1.13.x and up I just know in 1.12 you could just drag and drop a structure table into the map folder and have it be custom like that

———
73, KC1KSG

**Comment by ryandw11** [comment]
Minecraft Structures work different than World Edit schematics. I would love to add support for Structures also however I don't know if I would be able to get that to work.

**Comment by Mrs-Feathers** [comment]
would be interesting to note, after looking more into it, i was talking about datapacks being able to do that with vanilla worlds. i've never seen a plugin use minecraft .nbt structures. still though, thank you for the confirmation on a 1.14 version! very excited, as i think this might be one of the most important things about my server's survival world is the fact i have a rather large amount of schematics for your plugin to use in lower versions.. and so pre-generating a large map with all of them is quite fun for players. specially since the larger part of the structures are actually underground. and while it provides a larger opertunity for those spoil-sport xray users, it also protects player bases by making decoys for those xrayers who haven't been caught. otherwise, i think it quite fun to explore a world full of various structures. anyway, i guess i can say thank you for making my worlds fun :)

**Comment by ryandw11** [comment]
1.14.2 version has been added. Sorry for the long wait. Have been very busy.
