### ISSUE TITLE
Add Itemsadder Support to LootTables

### ISSUE THREAD

**Issue by FourRumble7698** [ryandw11/CustomStructures#98]
Hello, I'm creating an Aether prototype with this plugin and Itemsadder. But I have the limitation that I can't use custom items from Itemsadder in the LootTables. I hope it could be possible to add this support because it's really necessary for my project. Thanks

PD: I put this like a bug, but it's a characteristic to add, sorry I'm a beginner with this xD)

**Comment by ryandw11** [comment]
There is a custom item feature that you can use with loot tables. See this page: https://github.com/ryandw11/CustomStructures/wiki/Custom-Items

**Comment by FourRumble7698** [comment]
Omg, thanks. I have not seen very well this page. It works perfectly thanks so much for your support and for your useful plugin!
